<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { ElButton,ElDatePicker,ElDialog,ElEmpty,ElInput,ElOption,ElSelect,ElTable,ElTableColumn,ElTag } from 'element-plus'
import { ApiError } from '../api/client';import { listProjectFiles } from '../api/files';import { listWorkItems } from '../api/work-items'
import { createDesignAsset,createInterface,createMeetingRecord,createVendor,listDesignAssets,listInterfaces,listMeetingRecords,listVendors,submitInterface,submitMeetingRecord } from '../api/delivery-records'
const props=defineProps<{projectId:number;mode:'vendor'|'meeting'|'design';canWrite:boolean}>()
const rows=ref<any[]>([]),vendors=ref<any[]>([]),files=ref<any[]>([]),items=ref<any[]>([]);const loading=ref(false),saving=ref(false),error=ref(''),open=ref(false),kind=ref('')
const form=reactive<any>({})
const title=computed(()=>props.mode==='vendor'?'厂商与接口':props.mode==='meeting'?'会议与培训':'设计资料')
onMounted(load);watch(()=>[props.projectId,props.mode],load)
async function load(){loading.value=true;try{if(props.mode==='vendor'){const [v,i]=await Promise.all([listVendors(props.projectId),listInterfaces(props.projectId)]);vendors.value=v;rows.value=i}else if(props.mode==='meeting')rows.value=await listMeetingRecords(props.projectId);else rows.value=await listDesignAssets(props.projectId);error.value=''}catch(e){error.value=message(e)}finally{loading.value=false}}
async function start(type:string){kind.value=type;for(const k of Object.keys(form))delete form[k];if(type==='vendor')Object.assign(form,{name:'',contactName:'',contactPhone:'',contactEmail:'',systemName:'',notes:''});if(type==='interface')Object.assign(form,{vendorId:null,name:'',direction:'INBOUND',protocol:'HTTPS',endpoint:'',authMethod:'',fieldDescription:'',pushFrequency:'',integrationStatus:'NOT_STARTED',attachmentIds:[]});if(type==='meeting')Object.assign(form,{type:'REGULAR_MEETING',title:'',occurredAt:'',attendeesText:'',minutes:'',actionItems:'',attachmentIds:[]});if(type==='design')Object.assign(form,{type:'PROTOTYPE',title:'',stage:'',version:'',externalUrl:'',description:'',requirementWorkItemId:null,attachmentIds:[]});if(type!=='vendor'){try{const f=await listProjectFiles(props.projectId,{page:1,pageSize:100});files.value=f.data.filter(x=>x.status==='AVAILABLE')}catch{files.value=[]}}if(type==='design'){try{items.value=(await listWorkItems(props.projectId,{page:1,pageSize:100})).data}catch{items.value=[]}}open.value=true}
async function save(){saving.value=true;try{if(kind.value==='vendor')await createVendor(props.projectId,form);if(kind.value==='interface')await createInterface(props.projectId,form);if(kind.value==='meeting')await createMeetingRecord(props.projectId,{...form,attendees:form.attendeesText.split(',').map((x:string)=>x.trim()).filter(Boolean)});if(kind.value==='design')await createDesignAsset(props.projectId,form);open.value=false;await load()}catch(e){error.value=message(e)}finally{saving.value=false}}
async function submit(row:any){saving.value=true;try{props.mode==='vendor'?await submitInterface(props.projectId,row.id):await submitMeetingRecord(props.projectId,row.id);await load()}catch(e){error.value=message(e)}finally{saving.value=false}}
function message(e:unknown){return e instanceof ApiError?e.message:'操作失败，请稍后重试'}
</script>
<template><section class="subpanel"><div class="subpanel-heading"><div><p class="section-label">实施资料</p><h2>{{title}}</h2><p v-if="mode==='vendor'">保存厂商联系人、系统及接口联调信息。</p><p v-else-if="mode==='meeting'">沉淀例会、汇报和培训纪要与材料。</p><p v-else>管理原型、埋点图和设计说明。</p></div><div v-if="canWrite"><ElButton v-if="mode==='vendor'" @click="start('vendor')">新建厂商</ElButton><ElButton type="primary" @click="start(mode==='vendor'?'interface':mode)">新增{{mode==='vendor'?'接口':mode==='meeting'?'记录':'资料'}}</ElButton></div></div><p v-if="error" class="content-error">{{error}}</p><ElTable :data="rows" :aria-busy="loading"><ElTableColumn label="名称" min-width="220"><template #default="s"><strong>{{s.row.name||s.row.title}}</strong><span v-if="s.row.vendorName" class="cell-secondary">{{s.row.vendorName}}</span></template></ElTableColumn><ElTableColumn v-if="mode==='vendor'" label="协议/方向" min-width="150"><template #default="s">{{s.row.protocol}} · {{s.row.direction}}</template></ElTableColumn><ElTableColumn v-if="mode==='meeting'" label="时间" prop="occurredAt" min-width="180"/><ElTableColumn v-if="mode==='design'" label="阶段/版本" min-width="150"><template #default="s">{{s.row.stage||'-'}} · {{s.row.version||'-'}}</template></ElTableColumn><ElTableColumn v-if="mode!=='design'" label="状态" width="110"><template #default="s"><ElTag effect="plain">{{s.row.status==='SUBMITTED'?'已提交':'草稿'}}</ElTag></template></ElTableColumn><ElTableColumn v-if="canWrite&&mode!=='design'" label="操作" width="100"><template #default="s"><ElButton v-if="s.row.status==='DRAFT'" link type="primary" @click="submit(s.row)">正式提交</ElButton></template></ElTableColumn><template #empty><ElEmpty description="暂无记录"/></template></ElTable>
<ElDialog :model-value="open" title="新增记录" width="min(720px,94vw)" @close="open=false"><form class="record-form" @submit.prevent="save"><template v-if="kind==='vendor'"><label>厂商名称<ElInput v-model="form.name"/></label><label>联系人<ElInput v-model="form.contactName"/></label><label>联系电话<ElInput v-model="form.contactPhone"/></label><label>联系邮箱<ElInput v-model="form.contactEmail"/></label><label>系统名称<ElInput v-model="form.systemName"/></label></template><template v-else-if="kind==='interface'"><label>厂商<ElSelect v-model="form.vendorId"><ElOption v-for="v in vendors" :key="v.id" :label="v.name" :value="v.id"/></ElSelect></label><label>接口名称<ElInput v-model="form.name"/></label><label>方向<ElSelect v-model="form.direction"><ElOption label="接收" value="INBOUND"/><ElOption label="推送" value="OUTBOUND"/><ElOption label="双向" value="BIDIRECTIONAL"/></ElSelect></label><label>协议<ElInput v-model="form.protocol"/></label><label class="wide">地址<ElInput v-model="form.endpoint"/></label><label>鉴权方式<ElInput v-model="form.authMethod"/></label><label>推送频率<ElInput v-model="form.pushFrequency"/></label><label class="wide">字段说明<ElInput v-model="form.fieldDescription" type="textarea"/></label></template><template v-else-if="kind==='meeting'"><label>类型<ElSelect v-model="form.type"><ElOption label="例会" value="REGULAR_MEETING"/><ElOption label="汇报" value="PRESENTATION"/><ElOption label="培训" value="TRAINING"/></ElSelect></label><label>标题<ElInput v-model="form.title"/></label><label>发生时间<ElDatePicker v-model="form.occurredAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ"/></label><label>参会人<ElInput v-model="form.attendeesText" placeholder="逗号分隔"/></label><label class="wide">纪要<ElInput v-model="form.minutes" type="textarea"/></label><label class="wide">待办<ElInput v-model="form.actionItems" type="textarea"/></label></template><template v-else><label>类型<ElSelect v-model="form.type"><ElOption label="原型" value="PROTOTYPE"/><ElOption label="埋点图" value="TRACKING_MAP"/><ElOption label="设计说明" value="DESIGN_SPEC"/><ElOption label="其他" value="OTHER"/></ElSelect></label><label>标题<ElInput v-model="form.title"/></label><label>阶段<ElInput v-model="form.stage"/></label><label>版本<ElInput v-model="form.version"/></label><label class="wide">外链<ElInput v-model="form.externalUrl"/></label><label class="wide">关联需求<ElSelect v-model="form.requirementWorkItemId" clearable><ElOption v-for="i in items" :key="i.id" :label="i.title" :value="i.id"/></ElSelect></label><label class="wide">说明<ElInput v-model="form.description" type="textarea"/></label></template><label v-if="kind!=='vendor'" class="wide">附件<ElSelect v-model="form.attachmentIds" multiple><ElOption v-for="f in files" :key="f.id" :label="f.originalName" :value="f.id"/></ElSelect></label></form><template #footer><ElButton @click="open=false">取消</ElButton><ElButton type="primary" :loading="saving" @click="save">保存草稿</ElButton></template></ElDialog></section></template>
<style scoped>.record-form{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.record-form label{display:grid;gap:.4rem}.record-form .wide{grid-column:1/-1}@media(max-width:640px){.record-form{grid-template-columns:1fr}.record-form .wide{grid-column:auto}}</style>
