CREATE TABLE work_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'TODO',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    assignee_id BIGINT REFERENCES app_user (id),
    planned_start_date DATE,
    planned_end_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_work_item_type CHECK (type IN ('TASK', 'MILESTONE')),
    CONSTRAINT ck_work_item_status CHECK (
        status IN ('TODO', 'IN_PROGRESS', 'DONE', 'CANCELED')
    ),
    CONSTRAINT ck_work_item_priority CHECK (
        priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')
    ),
    CONSTRAINT ck_work_item_planned_dates CHECK (
        planned_end_date IS NULL OR planned_start_date IS NULL
            OR planned_end_date >= planned_start_date
    ),
    CONSTRAINT ck_work_item_actual_dates CHECK (
        actual_end_date IS NULL OR actual_start_date IS NULL
            OR actual_end_date >= actual_start_date
    )
);

CREATE INDEX idx_work_item_project_status
    ON work_item (project_id, status, updated_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_work_item_assignee
    ON work_item (assignee_id, status)
    WHERE deleted_at IS NULL AND assignee_id IS NOT NULL;

CREATE TABLE work_item_status_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_item_id BIGINT NOT NULL REFERENCES work_item (id) ON DELETE CASCADE,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    comment VARCHAR(1000),
    changed_by BIGINT NOT NULL REFERENCES app_user (id),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_work_item_log_from_status CHECK (
        from_status IS NULL OR from_status IN ('TODO', 'IN_PROGRESS', 'DONE', 'CANCELED')
    ),
    CONSTRAINT ck_work_item_log_to_status CHECK (
        to_status IN ('TODO', 'IN_PROGRESS', 'DONE', 'CANCELED')
    )
);

CREATE INDEX idx_work_item_status_log_item
    ON work_item_status_log (work_item_id, changed_at, id);

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('work_item:read', '查看工作项', 'work_item', 'read', '查看项目内的工作项与状态历史'),
    ('work_item:write', '维护工作项', 'work_item', 'write', '创建、修改和流转被授权的工作项'),
    ('work_item:delete', '删除工作项', 'work_item', 'delete', '软删除被授权的工作项');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER')
  AND permission.code IN ('work_item:read', 'work_item:write', 'work_item:delete');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('IMPLEMENTER', 'TESTER')
  AND permission.code IN ('work_item:read', 'work_item:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code = 'VISITOR'
  AND permission.code = 'work_item:read';
