ALTER TABLE work_item
    ADD CONSTRAINT uk_work_item_project_id UNIQUE (project_id, id);

CREATE TABLE work_item_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    source_work_item_id BIGINT NOT NULL,
    target_work_item_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_by BIGINT REFERENCES app_user (id),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_work_item_relation_source
        FOREIGN KEY (project_id, source_work_item_id)
        REFERENCES work_item (project_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_work_item_relation_target
        FOREIGN KEY (project_id, target_work_item_id)
        REFERENCES work_item (project_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_work_item_relation_type CHECK (
        type IN ('PARENT_CHILD', 'PRECEDES', 'BLOCKS')
    ),
    CONSTRAINT ck_work_item_relation_not_self CHECK (
        source_work_item_id <> target_work_item_id
    )
);

-- PRECEDES 和 BLOCKS 共享同一个依赖图，同方向不允许重复表达。
CREATE UNIQUE INDEX uk_work_item_relation_active
    ON work_item_relation (
        project_id,
        (CASE WHEN type = 'PARENT_CHILD' THEN 'HIERARCHY' ELSE 'DEPENDENCY' END),
        source_work_item_id,
        target_work_item_id
    )
    WHERE deleted_at IS NULL;

CREATE INDEX idx_work_item_relation_source
    ON work_item_relation (project_id, source_work_item_id, type)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_work_item_relation_target
    ON work_item_relation (project_id, target_work_item_id, type)
    WHERE deleted_at IS NULL;
