CREATE TABLE work_item_reminder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    work_item_id BIGINT NOT NULL,
    remind_at TIMESTAMPTZ NOT NULL,
    message VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dismissed_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_work_item_reminder_item
        FOREIGN KEY (project_id, work_item_id)
        REFERENCES work_item (project_id, id) ON DELETE CASCADE,
    CONSTRAINT ck_work_item_reminder_status CHECK (
        status IN ('PENDING', 'DISMISSED')
    ),
    CONSTRAINT ck_work_item_reminder_dismissed_at CHECK (
        (status = 'PENDING' AND dismissed_at IS NULL)
        OR (status = 'DISMISSED' AND dismissed_at IS NOT NULL)
    )
);

CREATE INDEX idx_work_item_reminder_personal_pending
    ON work_item_reminder (project_id, created_by, status, remind_at, id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_work_item_reminder_item
    ON work_item_reminder (project_id, work_item_id)
    WHERE deleted_at IS NULL;
