ALTER TABLE file_link DROP CONSTRAINT ck_file_link_business_type;
ALTER TABLE file_link ADD CONSTRAINT ck_file_link_business_type CHECK (
    business_type IN ('PROJECT_DOCUMENT', 'DEPLOYMENT_ASSET', 'KNOWLEDGE_ARTICLE')
);

CREATE TABLE knowledge_article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    scenario VARCHAR(500) NOT NULL,
    symptom TEXT NOT NULL,
    cause TEXT NOT NULL,
    solution TEXT NOT NULL,
    applicable_conditions TEXT,
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    review_comment VARCHAR(2000),
    reviewed_by BIGINT REFERENCES app_user (id),
    reviewed_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_knowledge_article_status CHECK (
        status IN ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED')
    ),
    CONSTRAINT ck_knowledge_article_tags_array CHECK (jsonb_typeof(tags) = 'array'),
    CONSTRAINT ck_knowledge_article_review CHECK (
        (status IN ('DRAFT', 'PENDING_REVIEW') AND reviewed_by IS NULL AND reviewed_at IS NULL)
        OR (status IN ('APPROVED', 'REJECTED') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);

CREATE INDEX idx_knowledge_article_project_status
    ON knowledge_article (project_id, status, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_knowledge_article_tags ON knowledge_article USING GIN (tags);

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('knowledge_article:read', '查看技术知识', 'knowledge_article', 'read', '查看被授权项目的技术知识'),
    ('knowledge_article:write', '维护技术知识', 'knowledge_article', 'write', '创建和维护被授权项目的技术知识草稿'),
    ('knowledge_article:review', '审核技术知识', 'knowledge_article', 'review', '审核被授权项目提交的技术知识');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER')
  AND permission.code IN (
      'knowledge_article:read', 'knowledge_article:write', 'knowledge_article:review'
  );

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code = 'IMPLEMENTER'
  AND permission.code IN ('knowledge_article:read', 'knowledge_article:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('TESTER', 'VISITOR')
  AND permission.code = 'knowledge_article:read';
