CREATE TABLE daily_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    report_date DATE NOT NULL,
    reporter_id BIGINT NOT NULL REFERENCES app_user (id),
    original_content TEXT NOT NULL,
    polished_content TEXT,
    work_hours NUMERIC(5,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    confirmed_by BIGINT REFERENCES app_user (id),
    confirmed_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_daily_report_hours CHECK (work_hours >= 0 AND work_hours <= 24),
    CONSTRAINT ck_daily_report_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_daily_report_confirmation CHECK (
        (status = 'DRAFT' AND confirmed_by IS NULL AND confirmed_at IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_daily_report_project_reporter_date
    ON daily_report (project_id, reporter_id, report_date)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_daily_report_project_date
    ON daily_report (project_id, report_date DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE daily_report_work_item (
    daily_report_id BIGINT NOT NULL REFERENCES daily_report (id) ON DELETE CASCADE,
    work_item_id BIGINT NOT NULL REFERENCES work_item (id),
    PRIMARY KEY (daily_report_id, work_item_id)
);

CREATE TABLE daily_report_deployment_record (
    daily_report_id BIGINT NOT NULL REFERENCES daily_report (id) ON DELETE CASCADE,
    deployment_record_id BIGINT NOT NULL REFERENCES deployment_record (id),
    PRIMARY KEY (daily_report_id, deployment_record_id)
);

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('daily_report:read', '查看日报', 'daily_report', 'read', '查看被授权项目的日报'),
    ('daily_report:write', '维护日报', 'daily_report', 'write', '创建和维护自己的日报草稿'),
    ('daily_report:confirm', '确认日报', 'daily_report', 'confirm', '确认自己或项目成员的日报');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id FROM app_role role CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER')
  AND permission.code IN ('daily_report:read', 'daily_report:write', 'daily_report:confirm');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id FROM app_role role CROSS JOIN app_permission permission
WHERE role.code IN ('IMPLEMENTER', 'TESTER')
  AND permission.code IN ('daily_report:read', 'daily_report:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id FROM app_role role CROSS JOIN app_permission permission
WHERE role.code = 'VISITOR' AND permission.code = 'daily_report:read';
