CREATE TABLE weekly_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    content TEXT NOT NULL,
    next_week_plan TEXT,
    generation_method VARCHAR(24) NOT NULL,
    daily_snapshot JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    confirmed_by BIGINT REFERENCES app_user (id),
    confirmed_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_weekly_report_dates CHECK (period_end >= period_start),
    CONSTRAINT ck_weekly_report_method CHECK (generation_method IN ('MANUAL', 'AUTO_SUMMARY')),
    CONSTRAINT ck_weekly_report_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_weekly_report_snapshot CHECK (jsonb_typeof(daily_snapshot) = 'array'),
    CONSTRAINT ck_weekly_report_confirmation CHECK (
        (status = 'DRAFT' AND confirmed_by IS NULL AND confirmed_at IS NULL)
        OR (status = 'CONFIRMED' AND confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)
    )
);
CREATE INDEX idx_weekly_report_project_period
    ON weekly_report (project_id, period_start DESC, id DESC) WHERE deleted_at IS NULL;

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('weekly_report:read', '查看周报', 'weekly_report', 'read', '查看被授权项目的周报'),
    ('weekly_report:write', '维护周报', 'weekly_report', 'write', '生成和维护周报草稿'),
    ('weekly_report:confirm', '确认周报', 'weekly_report', 'confirm', '确认项目周报');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id FROM app_role role CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER')
  AND permission.code IN ('weekly_report:read', 'weekly_report:write', 'weekly_report:confirm');
INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id FROM app_role role CROSS JOIN app_permission permission
WHERE role.code IN ('IMPLEMENTER', 'TESTER')
  AND permission.code IN ('weekly_report:read', 'weekly_report:write');
INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id FROM app_role role CROSS JOIN app_permission permission
WHERE role.code = 'VISITOR' AND permission.code = 'weekly_report:read';
