ALTER TABLE file_link DROP CONSTRAINT ck_file_link_business_type;
ALTER TABLE file_link ADD CONSTRAINT ck_file_link_business_type CHECK (
    business_type IN ('PROJECT_DOCUMENT','DEPLOYMENT_ASSET','KNOWLEDGE_ARTICLE',
                      'VENDOR_INTERFACE','MEETING_RECORD','DESIGN_ASSET')
);

CREATE TABLE vendor_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL, contact_name VARCHAR(100), contact_phone VARCHAR(100),
    contact_email VARCHAR(200), system_name VARCHAR(200), notes TEXT,
    created_by BIGINT NOT NULL REFERENCES app_user(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user(id), updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_vendor_project ON vendor_record(project_id,updated_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE integration_interface (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    vendor_id BIGINT NOT NULL REFERENCES vendor_record(id), name VARCHAR(200) NOT NULL,
    direction VARCHAR(20) NOT NULL, protocol VARCHAR(50) NOT NULL, endpoint VARCHAR(1000),
    auth_method VARCHAR(200), field_description TEXT, push_frequency VARCHAR(200),
    integration_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL REFERENCES app_user(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user(id), updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_interface_direction CHECK(direction IN('INBOUND','OUTBOUND','BIDIRECTIONAL')),
    CONSTRAINT ck_interface_integration_status CHECK(integration_status IN('NOT_STARTED','IN_PROGRESS','PASSED','BLOCKED')),
    CONSTRAINT ck_interface_status CHECK(status IN('DRAFT','SUBMITTED'))
);
CREATE INDEX idx_interface_project ON integration_interface(project_id,updated_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE meeting_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, occurred_at TIMESTAMPTZ NOT NULL,
    attendees JSONB NOT NULL DEFAULT '[]'::jsonb, minutes TEXT, action_items TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL REFERENCES app_user(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user(id), updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_meeting_type CHECK(type IN('REGULAR_MEETING','PRESENTATION','TRAINING')),
    CONSTRAINT ck_meeting_status CHECK(status IN('DRAFT','SUBMITTED')),
    CONSTRAINT ck_meeting_attendees CHECK(jsonb_typeof(attendees)='array')
);
CREATE INDEX idx_meeting_project_time ON meeting_record(project_id,occurred_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE design_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
    type VARCHAR(30) NOT NULL, title VARCHAR(200) NOT NULL, stage VARCHAR(100), version VARCHAR(50),
    external_url VARCHAR(1000), description TEXT, requirement_work_item_id BIGINT REFERENCES work_item(id),
    created_by BIGINT NOT NULL REFERENCES app_user(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user(id), updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_design_type CHECK(type IN('PROTOTYPE','TRACKING_MAP','DESIGN_SPEC','OTHER'))
);
CREATE INDEX idx_design_project ON design_asset(project_id,updated_at DESC) WHERE deleted_at IS NULL;

INSERT INTO app_permission(code,name,resource,action,description) VALUES
('vendor_record:read','查看厂商接口','vendor_record','read','查看厂商和接口记录'),
('vendor_record:write','维护厂商接口','vendor_record','write','维护厂商和接口记录'),
('meeting_record:read','查看会议培训','meeting_record','read','查看会议和培训记录'),
('meeting_record:write','维护会议培训','meeting_record','write','维护会议和培训记录'),
('design_asset:read','查看设计资料','design_asset','read','查看设计资料'),
('design_asset:write','维护设计资料','design_asset','write','维护设计资料');
INSERT INTO role_permission(role_id,permission_id)
SELECT r.id,p.id FROM app_role r CROSS JOIN app_permission p
WHERE r.code IN('ADMIN','PROJECT_MANAGER','IMPLEMENTER','TESTER')
AND p.code IN('vendor_record:read','vendor_record:write','meeting_record:read','meeting_record:write','design_asset:read','design_asset:write');
INSERT INTO role_permission(role_id,permission_id)
SELECT r.id,p.id FROM app_role r CROSS JOIN app_permission p WHERE r.code='VISITOR'
AND p.code IN('vendor_record:read','meeting_record:read','design_asset:read');
