CREATE TABLE file_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_group_id UUID NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    original_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    media_type VARCHAR(255),
    size_bytes BIGINT NOT NULL,
    sha256 CHAR(64),
    status VARCHAR(20) NOT NULL DEFAULT 'RESERVED',
    uploaded_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_file_asset_storage_key UNIQUE (storage_key),
    CONSTRAINT uk_file_asset_group_version UNIQUE (file_group_id, version),
    CONSTRAINT ck_file_asset_version CHECK (version > 0),
    CONSTRAINT ck_file_asset_size CHECK (size_bytes BETWEEN 0 AND 2147483648),
    CONSTRAINT ck_file_asset_sha256 CHECK (sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_file_asset_status CHECK (
        status IN ('RESERVED', 'UPLOADING', 'AVAILABLE', 'FAILED')
    )
);

CREATE INDEX idx_file_asset_group ON file_asset (file_group_id, version DESC);
CREATE INDEX idx_file_asset_uploader ON file_asset (uploaded_by, created_at DESC);

CREATE TABLE file_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_asset_id BIGINT NOT NULL REFERENCES file_asset (id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    business_type VARCHAR(64) NOT NULL,
    business_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_file_link_business UNIQUE (file_asset_id, business_type, business_id),
    CONSTRAINT ck_file_link_business_type CHECK (
        business_type IN ('PROJECT_DOCUMENT', 'DEPLOYMENT_ASSET')
    )
);

CREATE INDEX idx_file_link_project ON file_link (project_id, created_at DESC);
CREATE INDEX idx_file_link_business ON file_link (business_type, business_id);

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('file:read', '查看项目文件', 'file', 'read', '查看被授权项目的文件元数据和内容'),
    ('file:write', '维护项目文件', 'file', 'write', '上传和维护被授权项目的文件');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER')
  AND permission.code IN ('file:read', 'file:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code = 'IMPLEMENTER'
  AND permission.code IN ('file:read', 'file:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('TESTER', 'VISITOR')
  AND permission.code = 'file:read';
