CREATE TABLE deployment_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_group_id UUID NOT NULL,
    version INTEGER NOT NULL,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    asset_type VARCHAR(32) NOT NULL,
    version_label VARCHAR(64) NOT NULL,
    file_asset_id BIGINT NOT NULL REFERENCES file_asset (id),
    operating_system VARCHAR(100),
    architecture VARCHAR(64),
    environment VARCHAR(20) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    description TEXT,
    prerequisites TEXT,
    execution_instructions TEXT,
    rollback_instructions TEXT,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_deployment_asset_group_version UNIQUE (asset_group_id, version),
    CONSTRAINT ck_deployment_asset_version CHECK (version > 0),
    CONSTRAINT ck_deployment_asset_type CHECK (
        asset_type IN ('INSTALLATION_PACKAGE', 'SCRIPT', 'MANUAL', 'CONFIG_TEMPLATE', 'DEPENDENCY')
    ),
    CONSTRAINT ck_deployment_asset_environment CHECK (
        environment IN ('DEVELOPMENT', 'TESTING', 'STAGING', 'PRODUCTION', 'GENERAL')
    ),
    CONSTRAINT ck_deployment_asset_risk CHECK (
        risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    ),
    CONSTRAINT ck_deployment_asset_tags_array CHECK (jsonb_typeof(tags) = 'array'),
    CONSTRAINT ck_deployment_asset_script_instructions CHECK (
        asset_type <> 'SCRIPT' OR (
            NULLIF(BTRIM(prerequisites), '') IS NOT NULL
            AND NULLIF(BTRIM(execution_instructions), '') IS NOT NULL
            AND NULLIF(BTRIM(rollback_instructions), '') IS NOT NULL
        )
    )
);

CREATE INDEX idx_deployment_asset_project_created
    ON deployment_asset (project_id, created_at DESC, id DESC);
CREATE INDEX idx_deployment_asset_filters
    ON deployment_asset (project_id, asset_type, environment, risk_level);
CREATE INDEX idx_deployment_asset_tags ON deployment_asset USING GIN (tags);

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('deployment_asset:read', '查看部署资产', 'deployment_asset', 'read', '查看被授权项目的部署资产'),
    ('deployment_asset:write', '维护部署资产', 'deployment_asset', 'write', '创建被授权项目的部署资产版本');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER', 'IMPLEMENTER')
  AND permission.code IN ('deployment_asset:read', 'deployment_asset:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('TESTER', 'VISITOR')
  AND permission.code = 'deployment_asset:read';
