CREATE TABLE server_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    host VARCHAR(253) NOT NULL,
    port INTEGER NOT NULL,
    environment VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    operating_system VARCHAR(100),
    architecture VARCHAR(64),
    purpose VARCHAR(200),
    description TEXT,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_server_record_port CHECK (port BETWEEN 1 AND 65535),
    CONSTRAINT ck_server_record_environment CHECK (
        environment IN ('DEVELOPMENT', 'TESTING', 'STAGING', 'PRODUCTION', 'GENERAL')
    ),
    CONSTRAINT ck_server_record_status CHECK (
        status IN ('ACTIVE', 'MAINTENANCE', 'RETIRED')
    )
);

CREATE INDEX idx_server_record_project_updated
    ON server_record (project_id, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_server_record_filters
    ON server_record (project_id, environment, status)
    WHERE deleted_at IS NULL;

CREATE TABLE server_credential (
    server_id BIGINT PRIMARY KEY REFERENCES server_record (id) ON DELETE CASCADE,
    ciphertext BYTEA NOT NULL,
    nonce BYTEA NOT NULL,
    key_version VARCHAR(64) NOT NULL,
    updated_by BIGINT NOT NULL REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_server_credential_nonce_length CHECK (octet_length(nonce) = 12),
    CONSTRAINT ck_server_credential_ciphertext_present CHECK (octet_length(ciphertext) > 16)
);

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('server:read', '查看服务器档案', 'server', 'read', '查看被授权项目的服务器档案'),
    ('server:write', '维护服务器档案', 'server', 'write', '维护被授权项目的服务器档案'),
    ('server_credential:read', '查看服务器凭据', 'server_credential', 'read', '显式解密查看负责项目的服务器凭据'),
    ('server_credential:manage', '维护服务器凭据', 'server_credential', 'manage', '加密保存负责项目的服务器凭据');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER')
  AND permission.code IN (
      'server:read', 'server:write', 'server_credential:read', 'server_credential:manage'
  );

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code = 'IMPLEMENTER'
  AND permission.code IN ('server:read', 'server:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('TESTER', 'VISITOR')
  AND permission.code = 'server:read';
