CREATE TABLE environment_fingerprint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    environment VARCHAR(20) NOT NULL,
    operating_system VARCHAR(100) NOT NULL,
    os_version VARCHAR(100),
    kernel_version VARCHAR(100),
    architecture VARCHAR(64) NOT NULL,
    runtime_name VARCHAR(100),
    runtime_version VARCHAR(100),
    database_name VARCHAR(100),
    database_version VARCHAR(100),
    middlewares JSONB NOT NULL DEFAULT '[]'::JSONB,
    network_zone VARCHAR(100),
    tags JSONB NOT NULL DEFAULT '[]'::JSONB,
    notes TEXT,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_environment_fingerprint_environment CHECK (
        environment IN ('DEVELOPMENT', 'TESTING', 'STAGING', 'PRODUCTION', 'GENERAL')
    ),
    CONSTRAINT ck_environment_fingerprint_middlewares_array CHECK (
        jsonb_typeof(middlewares) = 'array'
    ),
    CONSTRAINT ck_environment_fingerprint_tags_array CHECK (jsonb_typeof(tags) = 'array')
);

CREATE UNIQUE INDEX uk_environment_fingerprint_project_name
    ON environment_fingerprint (project_id, LOWER(name))
    WHERE deleted_at IS NULL;
CREATE INDEX idx_environment_fingerprint_filters
    ON environment_fingerprint (
        project_id, environment, LOWER(operating_system), LOWER(architecture),
        LOWER(database_name)
    )
    WHERE deleted_at IS NULL;
CREATE INDEX idx_environment_fingerprint_middlewares
    ON environment_fingerprint USING GIN (middlewares);
CREATE INDEX idx_environment_fingerprint_tags
    ON environment_fingerprint USING GIN (tags);

CREATE TABLE deployment_solution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    environment_fingerprint_id BIGINT NOT NULL REFERENCES environment_fingerprint (id),
    name VARCHAR(200) NOT NULL,
    scenario VARCHAR(1000) NOT NULL,
    architecture_description TEXT NOT NULL,
    prerequisites TEXT NOT NULL,
    rollback_steps TEXT NOT NULL,
    risk_notes TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL REFERENCES app_user (id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_deployment_solution_status CHECK (
        status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')
    ),
    CONSTRAINT ck_deployment_solution_required_text CHECK (
        NULLIF(BTRIM(scenario), '') IS NOT NULL
        AND NULLIF(BTRIM(architecture_description), '') IS NOT NULL
        AND NULLIF(BTRIM(prerequisites), '') IS NOT NULL
        AND NULLIF(BTRIM(rollback_steps), '') IS NOT NULL
        AND NULLIF(BTRIM(risk_notes), '') IS NOT NULL
    )
);

CREATE INDEX idx_deployment_solution_project_updated
    ON deployment_solution (project_id, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_deployment_solution_filters
    ON deployment_solution (project_id, environment_fingerprint_id, status)
    WHERE deleted_at IS NULL;

CREATE TABLE deployment_solution_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solution_id BIGINT NOT NULL REFERENCES deployment_solution (id) ON DELETE CASCADE,
    step_order INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    instructions TEXT NOT NULL,
    deployment_asset_id BIGINT NOT NULL REFERENCES deployment_asset (id),
    parameters_template TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_deployment_solution_step_order UNIQUE (solution_id, step_order),
    CONSTRAINT ck_deployment_solution_step_order CHECK (step_order > 0),
    CONSTRAINT ck_deployment_solution_step_required_text CHECK (
        NULLIF(BTRIM(title), '') IS NOT NULL
        AND NULLIF(BTRIM(instructions), '') IS NOT NULL
    )
);

CREATE INDEX idx_deployment_solution_step_asset
    ON deployment_solution_step (deployment_asset_id);

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('environment_fingerprint:read', '查看环境指纹', 'environment_fingerprint', 'read', '查看被授权项目的规范化环境指纹'),
    ('environment_fingerprint:write', '维护环境指纹', 'environment_fingerprint', 'write', '维护被授权项目的环境指纹'),
    ('deployment_solution:read', '查看部署方案', 'deployment_solution', 'read', '查看被授权项目的部署方案与步骤'),
    ('deployment_solution:write', '维护部署方案', 'deployment_solution', 'write', '维护被授权项目的部署方案与资产编排');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER', 'IMPLEMENTER')
  AND permission.code IN (
      'environment_fingerprint:read', 'environment_fingerprint:write',
      'deployment_solution:read', 'deployment_solution:write'
  );

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('TESTER', 'VISITOR')
  AND permission.code IN ('environment_fingerprint:read', 'deployment_solution:read');
