CREATE TABLE deployment_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    server_id BIGINT NOT NULL REFERENCES server_record (id),
    solution_id BIGINT NOT NULL REFERENCES deployment_solution (id),
    environment_fingerprint_id BIGINT NOT NULL REFERENCES environment_fingerprint (id),
    result VARCHAR(20) NOT NULL,
    executed_by BIGINT NOT NULL REFERENCES app_user (id),
    executed_at TIMESTAMPTZ NOT NULL,
    exception_notes TEXT,
    notes TEXT,
    is_baseline BOOLEAN NOT NULL DEFAULT FALSE,
    server_snapshot JSONB NOT NULL,
    environment_snapshot JSONB NOT NULL,
    solution_snapshot JSONB NOT NULL,
    created_by BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_deployment_record_result CHECK (result IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_deployment_record_failed_notes CHECK (
        result <> 'FAILED' OR NULLIF(BTRIM(exception_notes), '') IS NOT NULL
    ),
    CONSTRAINT ck_deployment_record_baseline_success CHECK (
        is_baseline = FALSE OR result = 'SUCCESS'
    ),
    CONSTRAINT ck_deployment_record_server_snapshot CHECK (
        jsonb_typeof(server_snapshot) = 'object'
    ),
    CONSTRAINT ck_deployment_record_environment_snapshot CHECK (
        jsonb_typeof(environment_snapshot) = 'object'
    ),
    CONSTRAINT ck_deployment_record_solution_snapshot CHECK (
        jsonb_typeof(solution_snapshot) = 'object'
    )
);

CREATE INDEX idx_deployment_record_project_executed
    ON deployment_record (project_id, executed_at DESC, id DESC);
CREATE INDEX idx_deployment_record_filters
    ON deployment_record (project_id, result, server_id, is_baseline);
CREATE INDEX idx_deployment_record_baselines
    ON deployment_record (project_id, executed_at DESC)
    WHERE result = 'SUCCESS' AND is_baseline = TRUE;

INSERT INTO app_permission (code, name, resource, action, description)
VALUES
    ('deployment_record:read', '查看部署记录', 'deployment_record', 'read', '查看被授权项目的部署记录、执行快照和相似基线'),
    ('deployment_record:write', '维护部署记录', 'deployment_record', 'write', '创建部署记录并维护成功部署基线');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('ADMIN', 'PROJECT_MANAGER', 'IMPLEMENTER')
  AND permission.code IN ('deployment_record:read', 'deployment_record:write');

INSERT INTO role_permission (role_id, permission_id)
SELECT role.id, permission.id
FROM app_role role
CROSS JOIN app_permission permission
WHERE role.code IN ('TESTER', 'VISITOR')
  AND permission.code = 'deployment_record:read';
